export interface Question {
  id: number;
  category: string;
  skill: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  question: string;
  answer: string;
}

const questions: Question[] = [
  // ─── JAVASCRIPT ───────────────────────────────────────────────────────────
  { id: 1, category: "JavaScript", skill: "javascript", difficulty: "beginner", question: "What is the difference between var, let, and const?", answer: "var is function-scoped and hoisted. let is block-scoped and not hoisted to its value. const is block-scoped and cannot be reassigned (though objects it points to can be mutated). Use const by default, let when reassignment is needed, avoid var." },
  { id: 2, category: "JavaScript", skill: "javascript", difficulty: "beginner", question: "What is a closure in JavaScript?", answer: "A closure is a function that retains access to its lexical scope even when executed outside that scope. Inner functions close over variables of outer functions, keeping them alive. Used for data privacy, factory functions, and memoization." },
  { id: 3, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "Explain the event loop in JavaScript.", answer: "JavaScript is single-threaded. The event loop continuously checks the call stack and the task queue. When the stack is empty, it picks the next task from the queue (macrotasks like setTimeout) or microtask queue (Promises). Microtasks always run before the next macrotask." },
  { id: 4, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "What is the difference between == and ===?", answer: "== performs type coercion before comparison (loose equality). === compares value and type without coercion (strict equality). Always prefer === to avoid unexpected type conversions. 0 == false is true but 0 === false is false." },
  { id: 5, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "What are Promises and how do they differ from callbacks?", answer: "Promises represent a future value with three states: pending, fulfilled, rejected. Unlike callbacks, promises avoid callback hell with .then()/.catch() chaining, support async/await syntax, and can be composed with Promise.all, Promise.race, etc." },
  { id: 6, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "What is async/await and how does it work?", answer: "async/await is syntactic sugar over Promises. An async function always returns a Promise. await pauses execution inside the function until the Promise resolves, without blocking the thread. Error handling uses try/catch instead of .catch()." },
  { id: 7, category: "JavaScript", skill: "javascript", difficulty: "advanced", question: "Explain prototypal inheritance in JavaScript.", answer: "Every object has an internal [[Prototype]] reference to another object. Property lookup traverses the prototype chain. Object.create(), class syntax (which desugars to prototypes), and __proto__ all use this mechanism. Unlike classical OOP, objects inherit directly from objects." },
  { id: 8, category: "JavaScript", skill: "javascript", difficulty: "advanced", question: "What is the difference between call, apply, and bind?", answer: "All three set 'this' context. call(ctx, arg1, arg2) invokes immediately with individual args. apply(ctx, [args]) invokes immediately with an array. bind(ctx, arg1) returns a new function with 'this' permanently bound." },
  { id: 9, category: "JavaScript", skill: "javascript", difficulty: "advanced", question: "What is debouncing and throttling?", answer: "Debouncing delays function execution until after a specified wait period since the last call — useful for search inputs. Throttling ensures a function runs at most once per specified interval — useful for scroll or resize handlers. Both improve performance by limiting function call frequency." },
  { id: 10, category: "JavaScript", skill: "javascript", difficulty: "advanced", question: "What is a WeakMap and when would you use it?", answer: "WeakMap holds key-value pairs where keys must be objects and are held weakly (won't prevent GC). Unlike Map, it's not iterable and has no size. Used for caching computed values tied to object lifetimes and implementing private data for class instances." },
  { id: 11, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "What are generators in JavaScript?", answer: "Generators are functions that can pause execution with yield and resume later. Defined with function*. They return an iterator. Used for lazy evaluation, infinite sequences, async control flow, and implementing custom iterables." },
  { id: 12, category: "JavaScript", skill: "javascript", difficulty: "beginner", question: "What is hoisting in JavaScript?", answer: "Hoisting moves declarations (not initializations) to the top of their scope. var declarations are hoisted to function scope with value undefined. Function declarations are fully hoisted. let/const are in the temporal dead zone until their declaration line." },
  { id: 13, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "What is destructuring assignment?", answer: "Destructuring extracts values from arrays or properties from objects into distinct variables. Array: const [a, b] = [1, 2]. Object: const {name, age} = person. Supports defaults, renaming, rest patterns, and nested destructuring." },
  { id: 14, category: "JavaScript", skill: "javascript", difficulty: "intermediate", question: "What is the spread operator and rest parameters?", answer: "Spread (...arr) expands an iterable into individual elements. Used in function calls, array literals, and object literals. Rest (...args) collects multiple function arguments into an array. Spread spreads out, rest collects in." },
  { id: 15, category: "JavaScript", skill: "javascript", difficulty: "advanced", question: "Explain memoization in JavaScript.", answer: "Memoization caches the results of function calls keyed by their arguments. If called again with same args, returns cached result instead of recomputing. Implemented with a Map or plain object. Useful for pure functions with expensive computations. Tradeoff: memory for speed." },

  // ─── TYPESCRIPT ──────────────────────────────────────────────────────────
  { id: 16, category: "TypeScript", skill: "typescript", difficulty: "beginner", question: "What is TypeScript and why use it over JavaScript?", answer: "TypeScript is a statically-typed superset of JavaScript that compiles to plain JS. Benefits: compile-time type checking catches bugs early, better IDE autocompletion, self-documenting code, refactoring safety, and interfaces/generics for complex type relationships." },
  { id: 17, category: "TypeScript", skill: "typescript", difficulty: "intermediate", question: "What is the difference between interface and type in TypeScript?", answer: "Both define shapes of objects. Interfaces can be extended with 'extends' and support declaration merging. Types use '&' for intersection, support union types, mapped types, and conditional types. Use interface for object shapes, type for complex type operations." },
  { id: 18, category: "TypeScript", skill: "typescript", difficulty: "intermediate", question: "What are generics in TypeScript?", answer: "Generics allow writing reusable code that works with multiple types while preserving type safety. function identity<T>(arg: T): T. They're used in functions, interfaces, and classes. Constraints (T extends SomeType) limit what types can be passed." },
  { id: 19, category: "TypeScript", skill: "typescript", difficulty: "advanced", question: "What are conditional types in TypeScript?", answer: "Conditional types choose a type based on a condition: T extends U ? X : Y. Enables type-level if/else. Used for utility types like NonNullable, ReturnType, Parameters. The infer keyword extracts types within extends clauses." },
  { id: 20, category: "TypeScript", skill: "typescript", difficulty: "advanced", question: "What is the difference between unknown and any in TypeScript?", answer: "any opts out of type checking entirely — you can do anything with it. unknown is the type-safe counterpart — you must narrow it with type guards before using it. Prefer unknown over any when accepting values of uncertain type." },
  { id: 21, category: "TypeScript", skill: "typescript", difficulty: "intermediate", question: "What are utility types in TypeScript?", answer: "Built-in generic types: Partial<T> makes all properties optional. Required<T> makes all required. Readonly<T> prevents mutation. Pick<T,K> selects keys. Omit<T,K> removes keys. Record<K,V> creates a mapped type. ReturnType<T>, Parameters<T> extract function types." },
  { id: 22, category: "TypeScript", skill: "typescript", difficulty: "advanced", question: "What is a discriminated union in TypeScript?", answer: "A union type where each member has a common literal property (discriminant) that TypeScript uses to narrow types. Example: type Shape = {kind: 'circle', radius: number} | {kind: 'square', side: number}. Switch on 'kind' and TypeScript knows the exact type in each branch." },

  // ─── REACT ───────────────────────────────────────────────────────────────
  { id: 23, category: "React", skill: "react", difficulty: "beginner", question: "What is the Virtual DOM and how does React use it?", answer: "The Virtual DOM is a lightweight JavaScript representation of the real DOM. React renders components to a VDOM tree, then diffs it against the previous tree (reconciliation), and only updates the real DOM where changes occurred. This batched approach is more efficient than direct DOM manipulation." },
  { id: 24, category: "React", skill: "react", difficulty: "beginner", question: "What is the difference between state and props?", answer: "Props are read-only inputs passed from parent to child components. State is private, mutable data managed within a component that triggers re-renders when changed. Props flow down, events flow up. Never mutate props." },
  { id: 25, category: "React", skill: "react", difficulty: "intermediate", question: "What are React hooks and why were they introduced?", answer: "Hooks (introduced in React 16.8) let function components use state and lifecycle features. Rules: only call at top level, only in React functions. Core hooks: useState, useEffect, useContext, useRef, useMemo, useCallback, useReducer." },
  { id: 26, category: "React", skill: "react", difficulty: "intermediate", question: "Explain the useEffect hook and its dependency array.", answer: "useEffect runs side effects after render. The dependency array controls when it re-runs: [] runs once on mount, [dep1, dep2] runs when those values change, no array runs on every render. Return a cleanup function for subscriptions/timers." },
  { id: 27, category: "React", skill: "react", difficulty: "intermediate", question: "What is the difference between useMemo and useCallback?", answer: "useMemo memoizes a computed value, recomputing only when dependencies change. useCallback memoizes a function reference — avoids creating new functions on each render. useCallback(fn, deps) === useMemo(() => fn, deps)." },
  { id: 28, category: "React", skill: "react", difficulty: "intermediate", question: "What is Context API and when should you use it?", answer: "Context provides a way to pass data through the component tree without prop drilling. Use for: theme, locale, auth state, user preferences. Not ideal for high-frequency updates — use Zustand or Redux for that." },
  { id: 29, category: "React", skill: "react", difficulty: "advanced", question: "What is reconciliation in React?", answer: "Reconciliation is React's diffing algorithm that determines what changed between two render trees. Key heuristics: elements of different types produce different trees; keys help identify list items across renders. React uses an O(n) algorithm assuming keys are stable." },
  { id: 30, category: "React", skill: "react", difficulty: "advanced", question: "What are React Suspense and lazy loading?", answer: "React.lazy(() => import('./Component')) enables code splitting. Suspense wraps lazy components and shows a fallback while the component loads. Also used with data fetching libraries for declarative loading states." },
  { id: 31, category: "React", skill: "react", difficulty: "advanced", question: "What are custom hooks and why use them?", answer: "Custom hooks are functions starting with 'use' that can call other hooks. They extract and reuse stateful logic without changing component hierarchy. Example: useFetch, useLocalStorage, useDebounce. Makes components cleaner and logic testable in isolation." },

  // ─── NODE.JS ─────────────────────────────────────────────────────────────
  { id: 32, category: "Node.js", skill: "nodejs", difficulty: "beginner", question: "What is Node.js and what is it used for?", answer: "Node.js is a runtime that executes JavaScript server-side using Chrome's V8 engine. It's event-driven and non-blocking, making it great for I/O-intensive applications: REST APIs, real-time apps (chat, gaming), streaming, microservices." },
  { id: 33, category: "Node.js", skill: "nodejs", difficulty: "intermediate", question: "What is the Node.js event loop?", answer: "Node.js uses a single-threaded event loop with libuv for async I/O. Phases: timers, I/O callbacks, poll, check (setImmediate), close callbacks. process.nextTick and Promises run between phases. Understanding this is critical for avoiding blocking." },
  { id: 34, category: "Node.js", skill: "nodejs", difficulty: "intermediate", question: "What are streams in Node.js?", answer: "Streams are abstract interfaces for working with streaming data. Types: Readable, Writable, Duplex, Transform. Benefits: process data in chunks without loading entirely into memory. pipe() connects streams. Essential for file processing and HTTP." },
  { id: 35, category: "Node.js", skill: "nodejs", difficulty: "intermediate", question: "What is middleware in Express.js?", answer: "Middleware are functions with access to (req, res, next). They run in sequence between receiving a request and sending a response. Uses: logging, auth, body parsing, error handling, CORS. Call next() to pass to the next middleware." },

  // ─── PYTHON ──────────────────────────────────────────────────────────────
  { id: 36, category: "Python", skill: "python", difficulty: "beginner", question: "What is a list comprehension in Python?", answer: "List comprehensions create lists concisely: [expression for item in iterable if condition]. More readable and faster than equivalent for loops. Also: dict comprehensions {k:v}, set comprehensions {v}, generator expressions (v)." },
  { id: 37, category: "Python", skill: "python", difficulty: "intermediate", question: "What are decorators in Python?", answer: "Decorators are functions that take another function and extend its behavior without modifying it. Use @decorator syntax. Common uses: logging, timing, authentication (@login_required), caching (@lru_cache), retry logic." },
  { id: 38, category: "Python", skill: "python", difficulty: "intermediate", question: "What is the GIL (Global Interpreter Lock) in Python?", answer: "The GIL is a mutex in CPython that prevents multiple native threads from executing Python bytecode simultaneously. This means CPU-bound multi-threaded programs don't benefit from multiple cores. Solutions: multiprocessing (separate processes) or asyncio." },
  { id: 39, category: "Python", skill: "python", difficulty: "intermediate", question: "What is asyncio in Python?", answer: "asyncio is Python's standard library for writing concurrent code with async/await syntax. It uses an event loop (single-threaded) to schedule and run coroutines. Ideal for I/O-bound tasks. Frameworks: FastAPI, aiohttp build on it." },

  // ─── SQL / DATABASES ─────────────────────────────────────────────────────
  { id: 40, category: "SQL", skill: "sql", difficulty: "beginner", question: "What is the difference between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN?", answer: "INNER JOIN returns rows with matches in both tables. LEFT JOIN returns all left table rows plus matching right rows (nulls if no match). FULL OUTER JOIN returns all rows from both, with nulls for non-matches." },
  { id: 41, category: "SQL", skill: "sql", difficulty: "intermediate", question: "What are indexes in SQL and when should you use them?", answer: "Indexes are data structures that speed up SELECT queries at the cost of slower writes and more storage. Add indexes on: WHERE clause columns, JOIN keys, ORDER BY columns. Avoid indexing low-cardinality columns. Use EXPLAIN to analyze query plans." },
  { id: 42, category: "SQL", skill: "sql", difficulty: "intermediate", question: "What is a database transaction and what are ACID properties?", answer: "A transaction is a unit of work that's atomic. ACID: Atomicity (all or nothing), Consistency (data remains valid), Isolation (concurrent transactions don't interfere), Durability (committed data survives failures)." },
  { id: 43, category: "SQL", skill: "sql", difficulty: "advanced", question: "What are window functions in SQL?", answer: "Window functions perform calculations across rows related to the current row without collapsing rows like GROUP BY. Syntax: function() OVER (PARTITION BY col ORDER BY col). Examples: ROW_NUMBER(), RANK(), LAG(), LEAD(), SUM() OVER()." },
  { id: 44, category: "SQL", skill: "sql", difficulty: "intermediate", question: "What is normalization and what are the normal forms?", answer: "Normalization organizes database tables to reduce redundancy. 1NF: atomic values. 2NF: no partial dependencies. 3NF: no transitive dependencies. Higher forms exist but 3NF is usually sufficient for most applications." },

  // ─── POSTGRESQL ──────────────────────────────────────────────────────────
  { id: 45, category: "PostgreSQL", skill: "postgresql", difficulty: "intermediate", question: "What is JSONB in PostgreSQL?", answer: "JSONB stores JSON data in a decomposed binary format, supporting indexing and fast querying. Unlike JSON (stored as text), JSONB removes whitespace, reorders keys. Operators: ->, ->>, @>, ?. GIN indexes enable fast JSONB queries." },
  { id: 46, category: "PostgreSQL", skill: "postgresql", difficulty: "advanced", question: "What are CTEs (Common Table Expressions) in PostgreSQL?", answer: "CTEs define named temporary result sets using WITH clause. Benefits: readability, reusability, recursive CTEs for hierarchical data (WITH RECURSIVE). In PostgreSQL <12 CTEs were optimization fences; newer versions inline them by default." },

  // ─── MONGODB ─────────────────────────────────────────────────────────────
  { id: 47, category: "MongoDB", skill: "mongodb", difficulty: "beginner", question: "What is MongoDB and when would you use it over SQL?", answer: "MongoDB is a document-oriented NoSQL database storing data as BSON. Use it when: schema is flexible or evolving, data is naturally hierarchical/nested, horizontal scaling needed. Use SQL when: data is highly relational, strong consistency required." },
  { id: 48, category: "MongoDB", skill: "mongodb", difficulty: "intermediate", question: "What is the aggregation pipeline in MongoDB?", answer: "The aggregation pipeline processes documents through stages: $match (filter), $group, $project (reshape), $sort, $limit, $lookup (JOIN), $unwind. Each stage transforms the collection. More powerful than MapReduce for data transformation." },

  // ─── REDIS ───────────────────────────────────────────────────────────────
  { id: 49, category: "Redis", skill: "redis", difficulty: "beginner", question: "What is Redis and what are its main use cases?", answer: "Redis is an in-memory data structure store used as database, cache, and message broker. Data structures: strings, hashes, lists, sets, sorted sets, streams. Use cases: session storage, caching, rate limiting, pub/sub, leaderboards, real-time analytics." },
  { id: 50, category: "Redis", skill: "redis", difficulty: "intermediate", question: "What is Redis persistence (RDB vs AOF)?", answer: "RDB (Redis Database): point-in-time snapshots. Fast restarts, may lose recent data. AOF (Append Only File): logs every write operation. More durable, larger files, slower restart. Can combine both for optimal balance." },

  // ─── REST API ────────────────────────────────────────────────────────────
  { id: 51, category: "REST API", skill: "rest", difficulty: "beginner", question: "What are the HTTP methods and their meanings?", answer: "GET: retrieve resource (safe, idempotent). POST: create resource. PUT: replace entire resource (idempotent). PATCH: partial update. DELETE: remove resource. HEAD: GET without body. OPTIONS: describe allowed methods." },
  { id: 52, category: "REST API", skill: "rest", difficulty: "intermediate", question: "What is the difference between authentication and authorization?", answer: "Authentication: verifying identity (who are you?) — login, JWT validation, OAuth. Authorization: verifying permissions (what can you do?) — role checks, resource ownership. Auth always comes first. Never trust client-side authorization alone." },
  { id: 53, category: "REST API", skill: "rest", difficulty: "intermediate", question: "What are HTTP status codes and their categories?", answer: "2xx: Success (200 OK, 201 Created, 204 No Content). 3xx: Redirection (301, 302, 304). 4xx: Client errors (400, 401, 403, 404, 409, 422). 5xx: Server errors (500, 502, 503, 504). Use correct codes for semantic APIs." },

  // ─── DOCKER ──────────────────────────────────────────────────────────────
  { id: 54, category: "Docker", skill: "docker", difficulty: "beginner", question: "What is Docker and what problem does it solve?", answer: "Docker is a containerization platform that packages applications with their dependencies into isolated containers. Solves 'works on my machine' problem. Containers are lightweight (share host OS kernel), portable, consistent across environments." },
  { id: 55, category: "Docker", skill: "docker", difficulty: "intermediate", question: "What is Docker Compose?", answer: "Docker Compose defines multi-container applications in a YAML file. Specifies: services (containers), images/build contexts, environment variables, volumes, networks, dependencies. Commands: up, down, build, logs, exec. Great for local dev environments." },
  { id: 56, category: "Docker", skill: "docker", difficulty: "advanced", question: "What are Docker volumes and bind mounts?", answer: "Volumes are managed by Docker, stored in /var/lib/docker/volumes, persist beyond container lifecycle. Bind mounts map a host path to a container path — good for dev with live code reload. tmpfs mounts are in-memory. Use volumes for databases in production." },

  // ─── KUBERNETES ──────────────────────────────────────────────────────────
  { id: 57, category: "Kubernetes", skill: "kubernetes", difficulty: "beginner", question: "What is Kubernetes and what problem does it solve?", answer: "Kubernetes (K8s) is a container orchestration system that automates deployment, scaling, and management of containerized applications. Solves: running containers at scale, self-healing, rolling updates, service discovery, load balancing, secret management." },
  { id: 58, category: "Kubernetes", skill: "kubernetes", difficulty: "intermediate", question: "What is the difference between a Deployment, StatefulSet, and DaemonSet?", answer: "Deployment: manages stateless pods, rolling updates, rollback. StatefulSet: stateful apps (databases) with stable network IDs and persistent storage. DaemonSet: runs one pod per node for monitoring agents, log collectors, network plugins." },

  // ─── AWS ─────────────────────────────────────────────────────────────────
  { id: 59, category: "AWS", skill: "aws", difficulty: "beginner", question: "What is the difference between EC2, ECS, and Lambda?", answer: "EC2: virtual machines — you manage OS, runtime, scaling. ECS: container orchestration — you define tasks, AWS manages placement. Lambda: serverless functions — you provide code, AWS manages everything, billed per execution." },
  { id: 60, category: "AWS", skill: "aws", difficulty: "intermediate", question: "What is the difference between SQS and SNS?", answer: "SQS (Simple Queue Service): message queue, pull-based, one consumer per message, decouples producers/consumers. SNS (Simple Notification Service): pub/sub, push-based, fan-out to multiple subscribers. Use SNS → SQS fan-out pattern for reliable delivery." },

  // ─── GIT ─────────────────────────────────────────────────────────────────
  { id: 61, category: "Git", skill: "git", difficulty: "beginner", question: "What is the difference between git merge and git rebase?", answer: "Merge creates a merge commit preserving full history — non-destructive. Rebase moves commits on top of the target branch — linear history, no merge commit. Rebase rewrites history (never rebase shared branches). Use merge for feature branches into main." },
  { id: 62, category: "Git", skill: "git", difficulty: "intermediate", question: "What is git stash?", answer: "git stash temporarily shelves uncommitted changes so you can switch context. git stash pop restores and removes the stash; git stash apply keeps it. Useful for: switching branches without committing WIP, applying changes elsewhere." },

  // ─── SYSTEM DESIGN ───────────────────────────────────────────────────────
  { id: 63, category: "System Design", skill: "system design", difficulty: "intermediate", question: "What is horizontal vs vertical scaling?", answer: "Vertical scaling (scale up): add more resources to existing server. Simple but has limits. Horizontal scaling (scale out): add more servers and distribute load. Requires load balancing, stateless services. More resilient and theoretically unlimited." },
  { id: 64, category: "System Design", skill: "system design", difficulty: "advanced", question: "What is the CAP theorem?", answer: "CAP theorem states distributed systems can only guarantee 2 of 3: Consistency (all nodes see same data simultaneously), Availability (every request gets a response), Partition Tolerance (system continues despite network partitions). Choose CP, AP, or CA based on requirements." },
  { id: 65, category: "System Design", skill: "system design", difficulty: "advanced", question: "What are the common caching strategies?", answer: "Cache-aside (lazy loading): app checks cache, on miss fetches from DB and populates. Write-through: write to cache and DB simultaneously. Write-behind: write to cache, async write to DB. Cache-aside is most common. Invalidation: TTL, event-based, versioning." },
  { id: 66, category: "System Design", skill: "system design", difficulty: "advanced", question: "How would you design a URL shortener?", answer: "Components: API server, hash function (base62 encode auto-increment ID), storage (SQL mapping short→long), cache (Redis for popular URLs). Handle collisions, custom aliases, expiry, analytics. Scale: single DB handles 1B URLs; add read replicas for high traffic." },
  { id: 67, category: "System Design", skill: "system design", difficulty: "advanced", question: "How would you design a distributed rate limiter?", answer: "Algorithms: Token bucket (allows bursts), Leaky bucket (smooths traffic), Sliding window counter. Distributed: Redis with atomic INCR + EXPIRE, Lua script for atomicity. Rate limit by IP, user ID, or API key. Return 429 with Retry-After header." },

  // ─── SECURITY ────────────────────────────────────────────────────────────
  { id: 68, category: "Security", skill: "security", difficulty: "intermediate", question: "What is SQL injection and how do you prevent it?", answer: "SQL injection inserts malicious SQL into user input to manipulate queries. Prevention: parameterized queries/prepared statements (never string concatenate), stored procedures, input validation, least privilege DB accounts, ORMs which use prepared statements." },
  { id: 69, category: "Security", skill: "security", difficulty: "intermediate", question: "What is Cross-Site Scripting (XSS)?", answer: "XSS injects malicious scripts into web pages viewed by other users. Types: Stored (persisted in DB), Reflected (in URL), DOM-based. Prevention: escape output, Content Security Policy headers, HttpOnly cookies. React escapes JSX by default." },
  { id: 70, category: "Security", skill: "security", difficulty: "intermediate", question: "What is JWT and what are its security considerations?", answer: "JWT (JSON Web Token) is a compact signed token with header.payload.signature. Security: use HTTPS always, set short expiry, store in HttpOnly cookies (not localStorage — XSS risk), validate signature server-side, implement refresh token rotation." },
  { id: 71, category: "Security", skill: "security", difficulty: "advanced", question: "What is OAuth 2.0 and how does it work?", answer: "OAuth 2.0 is an authorization framework. Flows: Authorization Code (web apps — most secure, uses PKCE), Client Credentials (machine-to-machine), Device Code (TV/CLI). Steps: redirect to auth server, user authenticates, exchange code for access token." },

  // ─── CI/CD ───────────────────────────────────────────────────────────────
  { id: 72, category: "CI/CD", skill: "ci/cd", difficulty: "beginner", question: "What is the difference between Continuous Integration, Delivery, and Deployment?", answer: "CI: automatically build and test on every commit. CD (Delivery): CI + prepare releases to staging, manual gate to production. CD (Deployment): fully automated to production on every passing build. Each level builds on the previous." },
  { id: 73, category: "CI/CD", skill: "ci/cd", difficulty: "intermediate", question: "What is a blue-green deployment?", answer: "Blue-green deployment maintains two identical production environments. Blue is live, green is idle. Deploy to green, run tests, switch traffic. If issues arise, instant rollback by switching back to blue. Eliminates downtime and reduces deployment risk." },

  // ─── ALGORITHMS ──────────────────────────────────────────────────────────
  { id: 74, category: "Algorithms", skill: "algorithms", difficulty: "intermediate", question: "What is Big O notation?", answer: "Big O describes algorithmic time/space complexity as input grows. Common: O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n) linearithmic, O(n²) quadratic, O(2^n) exponential. Drop constants and lower terms. Guides algorithm selection for large datasets." },
  { id: 75, category: "Algorithms", skill: "algorithms", difficulty: "intermediate", question: "What is the difference between BFS and DFS?", answer: "BFS (Breadth-First Search): explores level by level using a queue. Finds shortest path in unweighted graphs. DFS (Depth-First Search): explores as deep as possible using a stack/recursion. Uses less memory for deep trees, finds all paths. Both: O(V+E) time." },
  { id: 76, category: "Algorithms", skill: "algorithms", difficulty: "advanced", question: "What is dynamic programming?", answer: "Dynamic programming solves complex problems by breaking them into overlapping subproblems, solving each once, and storing results (memoization top-down or tabulation bottom-up). Applies when: optimal substructure and overlapping subproblems exist. Examples: Fibonacci, knapsack, LCS." },

  // ─── CSS ─────────────────────────────────────────────────────────────────
  { id: 77, category: "CSS", skill: "css", difficulty: "beginner", question: "What is the CSS Box Model?", answer: "Every element is a box: content (innermost), padding (space inside border), border (visible edge), margin (space outside border). box-sizing: content-box (default), border-box (width includes padding/border — preferred). Understanding box model is fundamental for layout." },
  { id: 78, category: "CSS", skill: "css", difficulty: "intermediate", question: "What is the difference between Flexbox and CSS Grid?", answer: "Flexbox: one-dimensional layout (row OR column), content-first, items flow and wrap. Best for navigation, toolbars. Grid: two-dimensional (rows AND columns), layout-first, precise placement. Best for page layouts. Use both: Grid for overall layout, Flexbox for components." },
  { id: 79, category: "CSS", skill: "tailwind", difficulty: "beginner", question: "What is Tailwind CSS and how does it differ from traditional CSS frameworks?", answer: "Tailwind CSS is a utility-first CSS framework providing low-level utility classes (flex, pt-4, text-center) instead of pre-built components. You compose designs directly in HTML. Benefits: no unused CSS (purged), consistent design system, highly customizable." },

  // ─── NEXT.JS ─────────────────────────────────────────────────────────────
  { id: 80, category: "Next.js", skill: "next.js", difficulty: "intermediate", question: "What is the difference between SSR, SSG, and ISR in Next.js?", answer: "SSR (Server-Side Rendering): renders on each request. Fresh data, slower TTFB. SSG (Static Site Generation): renders at build time. Fast CDN serving, stale data. ISR (Incremental Static Regeneration): SSG + revalidate interval — regenerates pages in background." },
  { id: 81, category: "Next.js", skill: "next.js", difficulty: "advanced", question: "What are React Server Components?", answer: "RSC runs server-side and renders to a serialized format sent to the client. Benefits: direct DB/API access without API layer, reduced client JS bundle. Limitations: no useState/useEffect, no browser APIs. Client components (use client) can be nested inside server components." },

  // ─── DJANGO / FASTAPI ─────────────────────────────────────────────────────
  { id: 82, category: "Django", skill: "django", difficulty: "beginner", question: "What is Django and what makes it a batteries-included framework?", answer: "Django is a Python web framework following MVT pattern. 'Batteries included': ORM, admin interface, authentication, form handling, CSRF protection, i18n, testing utilities — all built-in. Follows convention over configuration. Ideal for data-driven apps and rapid development." },
  { id: 83, category: "FastAPI", skill: "fastapi", difficulty: "intermediate", question: "What is FastAPI and what are its main advantages?", answer: "FastAPI is a modern Python web framework for APIs. Built on Starlette and Pydantic. Key features: async/await support, automatic OpenAPI docs, type hints for validation, dependency injection, performance comparable to Node.js and Go." },

  // ─── AI/ML ───────────────────────────────────────────────────────────────
  { id: 84, category: "AI/ML", skill: "groq", difficulty: "beginner", question: "What is Groq and what makes it different from other AI inference providers?", answer: "Groq is an AI inference company using custom LPU (Language Processing Unit) chips instead of GPUs. LPUs deliver extremely fast inference (often 10-100x faster than GPU-based providers), deterministic performance, and low latency. Great for real-time applications." },
  { id: 85, category: "AI/ML", skill: "llm", difficulty: "intermediate", question: "What is prompt engineering?", answer: "Prompt engineering is crafting inputs to language models to get desired outputs. Techniques: few-shot prompting (examples in prompt), chain-of-thought (ask model to think step by step), role assignment (system prompts), output formatting, temperature control." },
  { id: 86, category: "AI/ML", skill: "llm", difficulty: "intermediate", question: "What is RAG (Retrieval-Augmented Generation)?", answer: "RAG combines retrieval of relevant documents with LLM generation. Process: embed query → search vector DB → include retrieved docs in prompt → LLM generates grounded answer. Reduces hallucinations, enables knowledge beyond training cutoff, allows proprietary data integration." },
  { id: 87, category: "AI/ML", skill: "machine learning", difficulty: "intermediate", question: "What is the difference between supervised and unsupervised learning?", answer: "Supervised learning trains on labeled data (input-output pairs) to predict outputs. Examples: classification, regression. Unsupervised learning finds patterns in unlabeled data. Examples: clustering (K-means), dimensionality reduction (PCA), anomaly detection." },
  { id: 88, category: "AI/ML", skill: "machine learning", difficulty: "intermediate", question: "What is overfitting and how do you prevent it?", answer: "Overfitting: model learns training data too well, including noise, and fails to generalize. Signs: high training accuracy, low test accuracy. Prevention: more training data, simpler model, regularization (L1/L2), dropout, cross-validation, early stopping." },

  // ─── DESIGN PATTERNS ─────────────────────────────────────────────────────
  { id: 89, category: "Design Patterns", skill: "design patterns", difficulty: "intermediate", question: "What is the Observer pattern?", answer: "Observer defines a one-to-many dependency: when one object (subject) changes state, all dependents (observers) are notified automatically. Used in: event systems, MVC, Redux subscriptions, reactive libraries (RxJS). Beware: memory leaks from unsubscribed observers." },
  { id: 90, category: "Design Patterns", skill: "design patterns", difficulty: "advanced", question: "What is SOLID principles?", answer: "S: Single Responsibility — one reason to change. O: Open/Closed — open for extension, closed for modification. L: Liskov Substitution — subtypes must be substitutable. I: Interface Segregation — many specific interfaces. D: Dependency Inversion — depend on abstractions. Foundation of maintainable OOP." },

  // ─── NETWORKING ──────────────────────────────────────────────────────────
  { id: 91, category: "Networking", skill: "networking", difficulty: "beginner", question: "What is the difference between TCP and UDP?", answer: "TCP: connection-oriented, reliable, ordered delivery, error checking, retransmission. Slower. Used for HTTP, email, file transfer. UDP: connectionless, no guarantee of delivery/order. Faster, lower overhead. Used for video streaming, gaming, DNS, VoIP." },
  { id: 92, category: "Networking", skill: "networking", difficulty: "intermediate", question: "What happens when you type a URL in a browser?", answer: "1. DNS lookup (cache → OS → resolver → root → TLD → authoritative). 2. TCP handshake. 3. TLS handshake (HTTPS). 4. HTTP request sent. 5. Server processes request. 6. HTTP response sent. 7. Browser parses HTML, fetches sub-resources, renders page." },
  { id: 93, category: "Networking", skill: "websockets", difficulty: "intermediate", question: "What are WebSockets and how do they differ from HTTP?", answer: "WebSockets provide full-duplex, persistent connections between client and server. Unlike HTTP (request-response, stateless), WebSockets maintain an open connection for real-time bidirectional communication. Used for: chat, live notifications, collaborative editing, gaming." },

  // ─── PERFORMANCE ─────────────────────────────────────────────────────────
  { id: 94, category: "Performance", skill: "performance", difficulty: "intermediate", question: "What are Core Web Vitals?", answer: "Google's user experience metrics: LCP (Largest Contentful Paint) — loading, target <2.5s. INP (Interaction to Next Paint) — interactivity, target <100ms. CLS (Cumulative Layout Shift) — visual stability, target <0.1. Used in Google ranking. Tools: Lighthouse, PageSpeed Insights." },

  // ─── GO / RUST ───────────────────────────────────────────────────────────
  { id: 95, category: "Go", skill: "golang", difficulty: "intermediate", question: "What are goroutines and channels in Go?", answer: "Goroutines are lightweight concurrent functions (go func()). Multiplexed onto OS threads by the Go runtime. Much cheaper than threads. Channels (make(chan Type)) enable safe communication between goroutines. 'Don't communicate by sharing memory; share memory by communicating.'" },
  { id: 96, category: "Rust", skill: "rust", difficulty: "intermediate", question: "What is Rust's ownership system?", answer: "Rust's ownership system guarantees memory safety without a garbage collector. Rules: each value has one owner, ownership moves on assignment (or is borrowed), value dropped when owner goes out of scope. Prevents data races at compile time without a GC." },

  // ─── KAFKA / ELASTICSEARCH ───────────────────────────────────────────────
  { id: 97, category: "Messaging", skill: "kafka", difficulty: "intermediate", question: "What is Apache Kafka and what are its core concepts?", answer: "Kafka is a distributed event streaming platform. Core: Topics (named streams), Partitions (ordered sequences), Producers (write messages), Consumers (read messages), Consumer Groups (each group gets all messages), Brokers (servers). Durable, high-throughput, replay support." },
  { id: 98, category: "Search", skill: "elasticsearch", difficulty: "intermediate", question: "What is Elasticsearch and how does it work?", answer: "Elasticsearch is a distributed search and analytics engine built on Apache Lucene. Documents stored as JSON in indices. Inverted index enables full-text search. Distributed: shards across nodes. DSL query language. Use cases: log analysis (ELK stack), full-text search, metrics." },

  // ─── OBSERVABILITY ───────────────────────────────────────────────────────
  { id: 99, category: "Observability", skill: "observability", difficulty: "intermediate", question: "What are the three pillars of observability?", answer: "Logs: timestamped records of discrete events — structured logs (JSON) are searchable. Metrics: numeric measurements over time — CPU, request rate, error rate (Prometheus). Traces: end-to-end request flows across services — shows latency, bottlenecks (Jaeger, OpenTelemetry)." },

  // ─── MICROSERVICES ───────────────────────────────────────────────────────
  { id: 100, category: "Architecture", skill: "microservices", difficulty: "intermediate", question: "What is the difference between microservices and monolithic architecture?", answer: "Monolith: single deployable unit, simple initially, hard to scale specific parts. Microservices: independently deployable services per domain, independent scaling, tech flexibility — but: network complexity, distributed systems challenges, operational overhead. Don't start with microservices." },
  { id: 101, category: "Architecture", skill: "microservices", difficulty: "advanced", question: "What is the Circuit Breaker pattern?", answer: "Circuit breaker prevents cascading failures in distributed systems. States: Closed (requests pass through), Open (short-circuit all requests, return fallback), Half-Open (allow some to test recovery). Opens after N consecutive failures, stays open for timeout. Libraries: Resilience4j, Polly." },

  // ─── GRAPHQL ─────────────────────────────────────────────────────────────
  { id: 102, category: "GraphQL", skill: "graphql", difficulty: "beginner", question: "What is GraphQL and how does it differ from REST?", answer: "GraphQL is a query language for APIs with one endpoint where clients specify exactly what data they need. Unlike REST (multiple endpoints, fixed response shapes), GraphQL eliminates over-fetching and under-fetching. Has strongly typed schema, introspection, and subscriptions." },
  { id: 103, category: "GraphQL", skill: "graphql", difficulty: "intermediate", question: "What is the N+1 problem in GraphQL?", answer: "N+1 occurs when resolving a list of N items each triggers an additional query — N+1 total queries instead of 2. Example: fetching 100 posts and each post resolver fetches its author separately = 101 queries. Solution: DataLoader batches and deduplicates calls within a request tick." },

  // ─── TERRAFORM / DEVOPS ──────────────────────────────────────────────────
  { id: 104, category: "DevOps", skill: "terraform", difficulty: "intermediate", question: "What is Infrastructure as Code (IaC)?", answer: "IaC manages and provisions infrastructure through machine-readable configuration files instead of manual UI processes. Benefits: version control, reproducibility, documentation, automation. Tools: Terraform (cloud-agnostic), AWS CloudFormation, Pulumi (code), Ansible (config management)." },
  { id: 105, category: "DevOps", skill: "devops", difficulty: "intermediate", question: "What is the difference between Terraform and Ansible?", answer: "Terraform: infrastructure provisioning (create/update/destroy cloud resources), declarative, has state management, idempotent. Ansible: configuration management (install software, configure servers), procedural, agentless (SSH). Often used together: Terraform provisions, Ansible configures." },

  // ─── FUNCTIONAL PROGRAMMING ──────────────────────────────────────────────
  { id: 106, category: "General Programming", skill: "functional programming", difficulty: "intermediate", question: "What are pure functions and why do they matter?", answer: "A pure function always returns the same output for the same input and has no side effects (no mutation, no I/O, no randomness). Benefits: predictable, testable, memoizable, composable, parallelizable. Foundation of functional programming and React's mental model." },

  // ─── TESTING ─────────────────────────────────────────────────────────────
  { id: 107, category: "Testing", skill: "testing", difficulty: "beginner", question: "What is the difference between unit, integration, and end-to-end tests?", answer: "Unit tests: test individual functions/components in isolation with mocks. Fast, numerous. Integration tests: test how units work together. E2E tests: test complete user flows in a browser (Playwright, Cypress). Test pyramid: many unit, fewer integration, few E2E." },
  { id: 108, category: "Testing", skill: "jest", difficulty: "intermediate", question: "What is the difference between a spy, stub, and mock?", answer: "Spy: wraps real implementation to record calls without changing behavior. Stub: replaces implementation with a controlled response. Mock: pre-programmed with expectations — fails the test if expectations aren't met. In Jest: jest.fn() is a mock, jest.spyOn() creates a spy." },

  // ─── SPRING / JAVA ───────────────────────────────────────────────────────
  { id: 109, category: "Spring", skill: "spring", difficulty: "intermediate", question: "What is Spring Boot and how does it differ from Spring Framework?", answer: "Spring Framework is a comprehensive Java application framework. Spring Boot is an opinionated layer on top: auto-configuration, embedded server (Tomcat), starter dependencies, production-ready metrics (Actuator). Eliminates XML config; convention over configuration." },
  { id: 110, category: "Java", skill: "java", difficulty: "intermediate", question: "What is the Java Stream API?", answer: "Streams provide functional-style operations on collections. Operations: filter(), map(), flatMap(), reduce(), collect(), sorted(), distinct(), limit(). Lazy evaluation — only computed when terminal operation called. Parallel streams (.parallelStream()) for multi-core processing." },

  // ─── PRISMA / ORM ────────────────────────────────────────────────────────
  { id: 111, category: "ORM", skill: "prisma", difficulty: "intermediate", question: "What is Prisma and how does it differ from traditional ORMs?", answer: "Prisma is a next-generation ORM for Node.js/TypeScript. Schema-first: define models in schema.prisma, auto-generate type-safe client. Features: fully typed queries, auto-completion, migrations (prisma migrate), Prisma Studio GUI. Separates schema, migrations, and client cleanly." },

  // ─── LINUX / OS ──────────────────────────────────────────────────────────
  { id: 112, category: "Linux", skill: "linux", difficulty: "intermediate", question: "What is a Linux file descriptor?", answer: "File descriptors are integers that reference open files, sockets, pipes, or devices. 0=stdin, 1=stdout, 2=stderr are always open. Every open() call returns a new FD. Used in system calls (read, write, close). lsof shows open FDs. FD leak causes resource exhaustion." },

  // ─── ACCESSIBILITY ───────────────────────────────────────────────────────
  { id: 113, category: "Accessibility", skill: "accessibility", difficulty: "intermediate", question: "What is ARIA and when should you use it?", answer: "ARIA (Accessible Rich Internet Applications) attributes enhance HTML semantics for assistive technologies. role='button', aria-label, aria-expanded, aria-live (dynamic regions), aria-hidden. First rule of ARIA: don't use it — prefer native semantic HTML. Use ARIA only when native elements can't achieve the semantics." },

  // ─── DATABASE DESIGN ─────────────────────────────────────────────────────
  { id: 114, category: "Database Design", skill: "database design", difficulty: "advanced", question: "What is database connection pooling?", answer: "Connection pooling maintains a pool of reusable database connections instead of opening/closing per request. Benefits: reduced connection overhead, limits concurrent connections (protects DB), faster response. Configure: min/max pool size, idle timeout, connection timeout." },
  { id: 115, category: "Database Design", skill: "database design", difficulty: "advanced", question: "What is consistent hashing?", answer: "Consistent hashing minimizes key remapping when nodes are added/removed. Nodes and keys are placed on a virtual ring. Key maps to nearest node clockwise. When a node is removed, only its keys move to the next node. Virtual nodes improve distribution. Used in Cassandra, distributed caches." },
];

const skillMap: Record<string, string> = {
  'js': 'javascript',
  'ts': 'typescript',
  'nodejs': 'nodejs',
  'node': 'nodejs',
  'reactjs': 'react',
  'vuejs': 'vue',
  'nextjs': 'next.js',
  'postgres': 'postgresql',
  'pg': 'postgresql',
  'mongo': 'mongodb',
  'k8s': 'kubernetes',
  'ml': 'machine learning',
  'ai': 'llm',
  'cicd': 'ci/cd',
  'ci/cd': 'ci/cd',
};

export function getAllQuestions(): Question[] {
  return questions;
}

export function getQuestionsBySkills(skillList: string[]): Question[] {
  const normalized = skillList.map(s => (skillMap[s.toLowerCase()] || s.toLowerCase()));
  return questions.filter(q => {
    const qSkill = q.skill.toLowerCase();
    const qCat = q.category.toLowerCase();
    return normalized.some(s =>
      qSkill.includes(s) || s.includes(qSkill) ||
      qCat.includes(s) || s.includes(qCat)
    );
  });
}

export function getCategories(): string[] {
  return [...new Set(questions.map(q => q.category))].sort();
}

export function getQuestionById(id: number): Question | undefined {
  return questions.find(q => q.id === id);
}
